// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file scalekit/v1/organizations/organizations.proto (package scalekit.v1.organizations, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminPortalLinkRequest, AdminPortalLinksResponse, CreateOrganizationRequest, CreateOrganizationResponse, DeleteOrganizationRequest, GenerateAdminPortalLinkResponse, GetOrganizationRequest, GetOrganizationResponse, ListOrganizationsRequest, ListOrganizationsResponse, UpdateOrganizationRequest, UpdateOrganizationResponse } from "./organizations_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scalekit.v1.organizations.OrganizationService
 */
export const OrganizationService = {
  typeName: "scalekit.v1.organizations.OrganizationService",
  methods: {
    /**
     * Create Organization
     *
     * @generated from rpc scalekit.v1.organizations.OrganizationService.CreateOrganization
     */
    createOrganization: {
      name: "CreateOrganization",
      I: CreateOrganizationRequest,
      O: CreateOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.organizations.OrganizationService.UpdateOrganization
     */
    updateOrganization: {
      name: "UpdateOrganization",
      I: UpdateOrganizationRequest,
      O: UpdateOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.organizations.OrganizationService.GetOrganization
     */
    getOrganization: {
      name: "GetOrganization",
      I: GetOrganizationRequest,
      O: GetOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.organizations.OrganizationService.ListOrganization
     */
    listOrganization: {
      name: "ListOrganization",
      I: ListOrganizationsRequest,
      O: ListOrganizationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an Organization
     *
     * @generated from rpc scalekit.v1.organizations.OrganizationService.DeleteOrganization
     */
    deleteOrganization: {
      name: "DeleteOrganization",
      I: DeleteOrganizationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Generate Portal Link for Org
     *
     * @generated from rpc scalekit.v1.organizations.OrganizationService.GenerateAdminPortalLink
     */
    generateAdminPortalLink: {
      name: "GenerateAdminPortalLink",
      I: AdminPortalLinkRequest,
      O: GenerateAdminPortalLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.organizations.OrganizationService.DeleteAdminPortalLink
     */
    deleteAdminPortalLink: {
      name: "DeleteAdminPortalLink",
      I: AdminPortalLinkRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.organizations.OrganizationService.GetAdminPortalLink
     */
    getAdminPortalLink: {
      name: "GetAdminPortalLink",
      I: AdminPortalLinkRequest,
      O: AdminPortalLinksResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

