// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file scalekit/v1/commons/commons.proto (package scalekit.v1.commons, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file scalekit/v1/commons/commons.proto.
 */
export const file_scalekit_v1_commons_commons: GenFile = /*@__PURE__*/
  fileDesc("CiFzY2FsZWtpdC92MS9jb21tb25zL2NvbW1vbnMucHJvdG8SE3NjYWxla2l0LnYxLmNvbW1vbnMqOQoKUmVnaW9uQ29kZRIbChdSRUdJT05fQ09ERV9VTlNQRUNJRklFRBAAEgYKAlVTEAESBgoCRVUQAkIzWjFnaXRodWIuY29tL3NjYWxla2l0LWluYy9zY2FsZWtpdC9wa2cvZ3JwYy9jb21tb25zYgZwcm90bzM");

/**
 * @generated from enum scalekit.v1.commons.RegionCode
 */
export enum RegionCode {
  /**
   *
   * If the region code is unspecified the selected region will automatically be decided based on the origin of the call.
   *
   * @generated from enum value: REGION_CODE_UNSPECIFIED = 0;
   */
  REGION_CODE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: US = 1;
   */
  US = 1,

  /**
   * @generated from enum value: EU = 2;
   */
  EU = 2,
}

/**
 * Describes the enum scalekit.v1.commons.RegionCode.
 */
export const RegionCodeSchema: GenEnum<RegionCode> = /*@__PURE__*/
  enumDesc(file_scalekit_v1_commons_commons, 0);

