"use strict";
// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file scalekit/v1/environments/environments.proto (package scalekit.v1.environments, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnvironmentService = void 0;
const environments_pb_js_1 = require("./environments_pb.js");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service scalekit.v1.environments.EnvironmentService
 */
exports.EnvironmentService = {
    typeName: "scalekit.v1.environments.EnvironmentService",
    methods: {
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.CreateEnvironment
         */
        createEnvironment: {
            name: "CreateEnvironment",
            I: environments_pb_js_1.CreateEnvironmentRequest,
            O: environments_pb_js_1.CreateEnvironmentResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.UpdateEnvironment
         */
        updateEnvironment: {
            name: "UpdateEnvironment",
            I: environments_pb_js_1.UpdateEnvironmentRequest,
            O: environments_pb_js_1.UpdateEnvironmentResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.UpdateEnvironmentDomain
         */
        updateEnvironmentDomain: {
            name: "UpdateEnvironmentDomain",
            I: environments_pb_js_1.UpdateEnvironmentDomainRequest,
            O: environments_pb_js_1.UpdateEnvironmentResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.GetEnvironment
         */
        getEnvironment: {
            name: "GetEnvironment",
            I: environments_pb_js_1.GetEnvironmentRequest,
            O: environments_pb_js_1.GetEnvironmentResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.ListEnvironment
         */
        listEnvironment: {
            name: "ListEnvironment",
            I: environments_pb_js_1.ListEnvironmentsRequest,
            O: environments_pb_js_1.ListEnvironmentsResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.DeleteEnvironment
         */
        deleteEnvironment: {
            name: "DeleteEnvironment",
            I: environments_pb_js_1.DeleteEnvironmentRequest,
            O: protobuf_1.Empty,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.GetRequiredDNSRecords
         */
        getRequiredDNSRecords: {
            name: "GetRequiredDNSRecords",
            I: environments_pb_js_1.GetDNSRecordsRequest,
            O: environments_pb_js_1.GetDNSRecordsResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.VerifyDNSRecords
         */
        verifyDNSRecords: {
            name: "VerifyDNSRecords",
            I: environments_pb_js_1.GetDNSRecordsRequest,
            O: protobuf_1.Empty,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.CreateCustomDomain
         */
        createCustomDomain: {
            name: "CreateCustomDomain",
            I: environments_pb_js_1.CreateCustomDomainRequest,
            O: environments_pb_js_1.CreateCustomDomainResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.environments.EnvironmentService.CheckCustomDomainStatus
         */
        checkCustomDomainStatus: {
            name: "CheckCustomDomainStatus",
            I: environments_pb_js_1.GetEnvironmentRequest,
            O: environments_pb_js_1.GetEnvironmentResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
//# sourceMappingURL=environments_connect.js.map