// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file scalekit/v1/environments/environments.proto (package scalekit.v1.environments, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateCustomDomainRequest, CreateCustomDomainResponse, CreateEnvironmentRequest, CreateEnvironmentResponse, DeleteEnvironmentRequest, GetDNSRecordsRequest, GetDNSRecordsResponse, GetEnvironmentRequest, GetEnvironmentResponse, ListEnvironmentsRequest, ListEnvironmentsResponse, UpdateEnvironmentDomainRequest, UpdateEnvironmentRequest, UpdateEnvironmentResponse } from "./environments_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scalekit.v1.environments.EnvironmentService
 */
export const EnvironmentService = {
  typeName: "scalekit.v1.environments.EnvironmentService",
  methods: {
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.CreateEnvironment
     */
    createEnvironment: {
      name: "CreateEnvironment",
      I: CreateEnvironmentRequest,
      O: CreateEnvironmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.UpdateEnvironment
     */
    updateEnvironment: {
      name: "UpdateEnvironment",
      I: UpdateEnvironmentRequest,
      O: UpdateEnvironmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.UpdateEnvironmentDomain
     */
    updateEnvironmentDomain: {
      name: "UpdateEnvironmentDomain",
      I: UpdateEnvironmentDomainRequest,
      O: UpdateEnvironmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.GetEnvironment
     */
    getEnvironment: {
      name: "GetEnvironment",
      I: GetEnvironmentRequest,
      O: GetEnvironmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.ListEnvironment
     */
    listEnvironment: {
      name: "ListEnvironment",
      I: ListEnvironmentsRequest,
      O: ListEnvironmentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.DeleteEnvironment
     */
    deleteEnvironment: {
      name: "DeleteEnvironment",
      I: DeleteEnvironmentRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.GetRequiredDNSRecords
     */
    getRequiredDNSRecords: {
      name: "GetRequiredDNSRecords",
      I: GetDNSRecordsRequest,
      O: GetDNSRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.VerifyDNSRecords
     */
    verifyDNSRecords: {
      name: "VerifyDNSRecords",
      I: GetDNSRecordsRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.CreateCustomDomain
     */
    createCustomDomain: {
      name: "CreateCustomDomain",
      I: CreateCustomDomainRequest,
      O: CreateCustomDomainResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.environments.EnvironmentService.CheckCustomDomainStatus
     */
    checkCustomDomainStatus: {
      name: "CheckCustomDomainStatus",
      I: GetEnvironmentRequest,
      O: GetEnvironmentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

