"use strict";
// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file scalekit/v1/directories/directories.proto (package scalekit.v1.directories, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.TriggerDirectorySyncRequest = exports.DeleteDirectoryRequest = exports.UpdateAttributesResponse = exports.AttributeMapping = exports.AttributeMappings = exports.UpdateAttributesRequest = exports.RoleAssignment = exports.AssignRolesResponse = exports.RoleAssignments = exports.AssignRolesRequest = exports.Stats = exports.Secret = exports.RegenerateDirectorySecretResponse = exports.RegenerateDirectorySecretRequest = exports.CreateDirectorySecretResponse = exports.CreateDirectorySecretRequest = exports.DirectoryGroup = exports.ExternalGroup = exports.DirectoryUser = exports.DirectoryMapping = exports.ToggleDirectoryResponse = exports.ToggleDirectoryRequest = exports.Directory = exports.ListDirectoryGroupsSummaryRequest = exports.ListDirectoryGroupsResponse = exports.ListDirectoryGroupsRequest = exports.ListDirectoryUsersResponse = exports.ListDirectoryUsersRequest = exports.ListDirectoriesResponse = exports.ListDirectoriesRequest = exports.AssignGroupsForDirectoryRequest = exports.UpdateDirectoryResponse = exports.UpdateDirectory = exports.UpdateDirectoryRequest = exports.CreateDirectoryResponse = exports.CreateDirectory = exports.CreateDirectoryRequest = exports.GetDirectoryResponse = exports.GetDirectoryRequest = exports.SecretStatus = exports.DirectoryStatus = exports.DirectoryProvider = exports.DirectoryType = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from enum scalekit.v1.directories.DirectoryType
 */
var DirectoryType;
(function (DirectoryType) {
    /**
     * @generated from enum value: DIRECTORY_TYPE_UNSPECIFIED = 0;
     */
    DirectoryType[DirectoryType["DIRECTORY_TYPE_UNSPECIFIED"] = 0] = "DIRECTORY_TYPE_UNSPECIFIED";
    /**
     * @generated from enum value: SCIM = 1;
     */
    DirectoryType[DirectoryType["SCIM"] = 1] = "SCIM";
    /**
     * @generated from enum value: LDAP = 2;
     */
    DirectoryType[DirectoryType["LDAP"] = 2] = "LDAP";
    /**
     * @generated from enum value: POLL = 3;
     */
    DirectoryType[DirectoryType["POLL"] = 3] = "POLL";
})(DirectoryType || (exports.DirectoryType = DirectoryType = {}));
// Retrieve enum metadata with: proto3.getEnumType(DirectoryType)
protobuf_1.proto3.util.setEnumType(DirectoryType, "scalekit.v1.directories.DirectoryType", [
    { no: 0, name: "DIRECTORY_TYPE_UNSPECIFIED" },
    { no: 1, name: "SCIM" },
    { no: 2, name: "LDAP" },
    { no: 3, name: "POLL" },
]);
/**
 * @generated from enum scalekit.v1.directories.DirectoryProvider
 */
var DirectoryProvider;
(function (DirectoryProvider) {
    /**
     * @generated from enum value: DIRECTORY_PROVIDER_UNSPECIFIED = 0;
     */
    DirectoryProvider[DirectoryProvider["DIRECTORY_PROVIDER_UNSPECIFIED"] = 0] = "DIRECTORY_PROVIDER_UNSPECIFIED";
    /**
     * @generated from enum value: OKTA = 1;
     */
    DirectoryProvider[DirectoryProvider["OKTA"] = 1] = "OKTA";
    /**
     * @generated from enum value: GOOGLE = 2;
     */
    DirectoryProvider[DirectoryProvider["GOOGLE"] = 2] = "GOOGLE";
    /**
     * @generated from enum value: MICROSOFT_AD = 3;
     */
    DirectoryProvider[DirectoryProvider["MICROSOFT_AD"] = 3] = "MICROSOFT_AD";
    /**
     * @generated from enum value: AUTH0 = 4;
     */
    DirectoryProvider[DirectoryProvider["AUTH0"] = 4] = "AUTH0";
    /**
     * @generated from enum value: ONELOGIN = 5;
     */
    DirectoryProvider[DirectoryProvider["ONELOGIN"] = 5] = "ONELOGIN";
    /**
     * @generated from enum value: JUMPCLOUD = 6;
     */
    DirectoryProvider[DirectoryProvider["JUMPCLOUD"] = 6] = "JUMPCLOUD";
    /**
     * @generated from enum value: PING_IDENTITY = 7;
     */
    DirectoryProvider[DirectoryProvider["PING_IDENTITY"] = 7] = "PING_IDENTITY";
})(DirectoryProvider || (exports.DirectoryProvider = DirectoryProvider = {}));
// Retrieve enum metadata with: proto3.getEnumType(DirectoryProvider)
protobuf_1.proto3.util.setEnumType(DirectoryProvider, "scalekit.v1.directories.DirectoryProvider", [
    { no: 0, name: "DIRECTORY_PROVIDER_UNSPECIFIED" },
    { no: 1, name: "OKTA" },
    { no: 2, name: "GOOGLE" },
    { no: 3, name: "MICROSOFT_AD" },
    { no: 4, name: "AUTH0" },
    { no: 5, name: "ONELOGIN" },
    { no: 6, name: "JUMPCLOUD" },
    { no: 7, name: "PING_IDENTITY" },
]);
/**
 * @generated from enum scalekit.v1.directories.DirectoryStatus
 */
var DirectoryStatus;
(function (DirectoryStatus) {
    /**
     * @generated from enum value: DIRECTORY_STATUS_UNSPECIFIED = 0;
     */
    DirectoryStatus[DirectoryStatus["DIRECTORY_STATUS_UNSPECIFIED"] = 0] = "DIRECTORY_STATUS_UNSPECIFIED";
    /**
     * @generated from enum value: DRAFT = 1;
     */
    DirectoryStatus[DirectoryStatus["DRAFT"] = 1] = "DRAFT";
    /**
     * @generated from enum value: IN_PROGRESS = 2;
     */
    DirectoryStatus[DirectoryStatus["IN_PROGRESS"] = 2] = "IN_PROGRESS";
    /**
     * @generated from enum value: COMPLETED = 3;
     */
    DirectoryStatus[DirectoryStatus["COMPLETED"] = 3] = "COMPLETED";
})(DirectoryStatus || (exports.DirectoryStatus = DirectoryStatus = {}));
// Retrieve enum metadata with: proto3.getEnumType(DirectoryStatus)
protobuf_1.proto3.util.setEnumType(DirectoryStatus, "scalekit.v1.directories.DirectoryStatus", [
    { no: 0, name: "DIRECTORY_STATUS_UNSPECIFIED" },
    { no: 1, name: "DRAFT" },
    { no: 2, name: "IN_PROGRESS" },
    { no: 3, name: "COMPLETED" },
]);
/**
 * @generated from enum scalekit.v1.directories.SecretStatus
 */
var SecretStatus;
(function (SecretStatus) {
    /**
     * @generated from enum value: ACTIVE = 0;
     */
    SecretStatus[SecretStatus["ACTIVE"] = 0] = "ACTIVE";
    /**
     * @generated from enum value: INACTIVE = 1;
     */
    SecretStatus[SecretStatus["INACTIVE"] = 1] = "INACTIVE";
})(SecretStatus || (exports.SecretStatus = SecretStatus = {}));
// Retrieve enum metadata with: proto3.getEnumType(SecretStatus)
protobuf_1.proto3.util.setEnumType(SecretStatus, "scalekit.v1.directories.SecretStatus", [
    { no: 0, name: "ACTIVE" },
    { no: 1, name: "INACTIVE" },
]);
/**
 * @generated from message scalekit.v1.directories.GetDirectoryRequest
 */
class GetDirectoryRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string organization_id = 2;
         */
        this.organizationId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GetDirectoryRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetDirectoryRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetDirectoryRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetDirectoryRequest, a, b);
    }
}
exports.GetDirectoryRequest = GetDirectoryRequest;
GetDirectoryRequest.runtime = protobuf_1.proto3;
GetDirectoryRequest.typeName = "scalekit.v1.directories.GetDirectoryRequest";
GetDirectoryRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.GetDirectoryResponse
 */
class GetDirectoryResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GetDirectoryResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetDirectoryResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetDirectoryResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetDirectoryResponse, a, b);
    }
}
exports.GetDirectoryResponse = GetDirectoryResponse;
GetDirectoryResponse.runtime = protobuf_1.proto3;
GetDirectoryResponse.typeName = "scalekit.v1.directories.GetDirectoryResponse";
GetDirectoryResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "directory", kind: "message", T: Directory },
]);
/**
 * @generated from message scalekit.v1.directories.CreateDirectoryRequest
 */
class CreateDirectoryRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateDirectoryRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateDirectoryRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateDirectoryRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateDirectoryRequest, a, b);
    }
}
exports.CreateDirectoryRequest = CreateDirectoryRequest;
CreateDirectoryRequest.runtime = protobuf_1.proto3;
CreateDirectoryRequest.typeName = "scalekit.v1.directories.CreateDirectoryRequest";
CreateDirectoryRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "directory", kind: "message", T: CreateDirectory },
]);
/**
 * @generated from message scalekit.v1.directories.CreateDirectory
 */
class CreateDirectory extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: scalekit.v1.directories.DirectoryType directory_type = 1;
         */
        this.directoryType = DirectoryType.DIRECTORY_TYPE_UNSPECIFIED;
        /**
         * @generated from field: scalekit.v1.directories.DirectoryProvider directory_provider = 2;
         */
        this.directoryProvider = DirectoryProvider.DIRECTORY_PROVIDER_UNSPECIFIED;
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateDirectory().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateDirectory().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateDirectory().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateDirectory, a, b);
    }
}
exports.CreateDirectory = CreateDirectory;
CreateDirectory.runtime = protobuf_1.proto3;
CreateDirectory.typeName = "scalekit.v1.directories.CreateDirectory";
CreateDirectory.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "directory_type", kind: "enum", T: protobuf_1.proto3.getEnumType(DirectoryType) },
    { no: 2, name: "directory_provider", kind: "enum", T: protobuf_1.proto3.getEnumType(DirectoryProvider) },
]);
/**
 * @generated from message scalekit.v1.directories.CreateDirectoryResponse
 */
class CreateDirectoryResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateDirectoryResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateDirectoryResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateDirectoryResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateDirectoryResponse, a, b);
    }
}
exports.CreateDirectoryResponse = CreateDirectoryResponse;
CreateDirectoryResponse.runtime = protobuf_1.proto3;
CreateDirectoryResponse.typeName = "scalekit.v1.directories.CreateDirectoryResponse";
CreateDirectoryResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "directory", kind: "message", T: Directory },
]);
/**
 * @generated from message scalekit.v1.directories.UpdateDirectoryRequest
 */
class UpdateDirectoryRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string organization_id = 2;
         */
        this.organizationId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateDirectoryRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateDirectoryRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateDirectoryRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateDirectoryRequest, a, b);
    }
}
exports.UpdateDirectoryRequest = UpdateDirectoryRequest;
UpdateDirectoryRequest.runtime = protobuf_1.proto3;
UpdateDirectoryRequest.typeName = "scalekit.v1.directories.UpdateDirectoryRequest";
UpdateDirectoryRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "directory", kind: "message", T: UpdateDirectory },
]);
/**
 * @generated from message scalekit.v1.directories.UpdateDirectory
 */
class UpdateDirectory extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string name = 2;
         */
        this.name = "";
        /**
         * @generated from field: scalekit.v1.directories.DirectoryType directory_type = 3;
         */
        this.directoryType = DirectoryType.DIRECTORY_TYPE_UNSPECIFIED;
        /**
         * @generated from field: bool enabled = 7;
         */
        this.enabled = false;
        /**
         * @generated from field: scalekit.v1.directories.DirectoryProvider directory_provider = 8;
         */
        this.directoryProvider = DirectoryProvider.DIRECTORY_PROVIDER_UNSPECIFIED;
        /**
         * @generated from field: scalekit.v1.directories.DirectoryStatus status = 9;
         */
        this.status = DirectoryStatus.DIRECTORY_STATUS_UNSPECIFIED;
        /**
         * @generated from field: repeated scalekit.v1.directories.DirectoryMapping mappings = 10;
         */
        this.mappings = [];
        /**
         * @generated from field: repeated scalekit.v1.directories.ExternalGroup groups = 15;
         */
        this.groups = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateDirectory().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateDirectory().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateDirectory().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateDirectory, a, b);
    }
}
exports.UpdateDirectory = UpdateDirectory;
UpdateDirectory.runtime = protobuf_1.proto3;
UpdateDirectory.typeName = "scalekit.v1.directories.UpdateDirectory";
UpdateDirectory.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "directory_type", kind: "enum", T: protobuf_1.proto3.getEnumType(DirectoryType) },
    { no: 7, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "directory_provider", kind: "enum", T: protobuf_1.proto3.getEnumType(DirectoryProvider) },
    { no: 9, name: "status", kind: "enum", T: protobuf_1.proto3.getEnumType(DirectoryStatus) },
    { no: 10, name: "mappings", kind: "message", T: DirectoryMapping, repeated: true },
    { no: 15, name: "groups", kind: "message", T: ExternalGroup, repeated: true },
]);
/**
 * @generated from message scalekit.v1.directories.UpdateDirectoryResponse
 */
class UpdateDirectoryResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateDirectoryResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateDirectoryResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateDirectoryResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateDirectoryResponse, a, b);
    }
}
exports.UpdateDirectoryResponse = UpdateDirectoryResponse;
UpdateDirectoryResponse.runtime = protobuf_1.proto3;
UpdateDirectoryResponse.typeName = "scalekit.v1.directories.UpdateDirectoryResponse";
UpdateDirectoryResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "directory", kind: "message", T: Directory },
]);
/**
 * @generated from message scalekit.v1.directories.AssignGroupsForDirectoryRequest
 */
class AssignGroupsForDirectoryRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string organization_id = 2;
         */
        this.organizationId = "";
        /**
         * @generated from field: repeated string external_ids = 3;
         */
        this.externalIds = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AssignGroupsForDirectoryRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AssignGroupsForDirectoryRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AssignGroupsForDirectoryRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AssignGroupsForDirectoryRequest, a, b);
    }
}
exports.AssignGroupsForDirectoryRequest = AssignGroupsForDirectoryRequest;
AssignGroupsForDirectoryRequest.runtime = protobuf_1.proto3;
AssignGroupsForDirectoryRequest.typeName = "scalekit.v1.directories.AssignGroupsForDirectoryRequest";
AssignGroupsForDirectoryRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "external_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
]);
/**
 * @generated from message scalekit.v1.directories.ListDirectoriesRequest
 */
class ListDirectoriesRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListDirectoriesRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListDirectoriesRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListDirectoriesRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListDirectoriesRequest, a, b);
    }
}
exports.ListDirectoriesRequest = ListDirectoriesRequest;
ListDirectoriesRequest.runtime = protobuf_1.proto3;
ListDirectoriesRequest.typeName = "scalekit.v1.directories.ListDirectoriesRequest";
ListDirectoriesRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.ListDirectoriesResponse
 */
class ListDirectoriesResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.directories.Directory directories = 1;
         */
        this.directories = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListDirectoriesResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListDirectoriesResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListDirectoriesResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListDirectoriesResponse, a, b);
    }
}
exports.ListDirectoriesResponse = ListDirectoriesResponse;
ListDirectoriesResponse.runtime = protobuf_1.proto3;
ListDirectoriesResponse.typeName = "scalekit.v1.directories.ListDirectoriesResponse";
ListDirectoriesResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "directories", kind: "message", T: Directory, repeated: true },
]);
/**
 * @generated from message scalekit.v1.directories.ListDirectoryUsersRequest
 */
class ListDirectoryUsersRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string directory_id = 2;
         */
        this.directoryId = "";
        /**
         * @generated from field: uint32 page_size = 3;
         */
        this.pageSize = 0;
        /**
         * @generated from field: string page_token = 4;
         */
        this.pageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListDirectoryUsersRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListDirectoryUsersRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListDirectoryUsersRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListDirectoryUsersRequest, a, b);
    }
}
exports.ListDirectoryUsersRequest = ListDirectoryUsersRequest;
ListDirectoryUsersRequest.runtime = protobuf_1.proto3;
ListDirectoryUsersRequest.typeName = "scalekit.v1.directories.ListDirectoryUsersRequest";
ListDirectoryUsersRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "directory_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "include_detail", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "directory_group_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "updated_after", kind: "message", T: protobuf_1.Timestamp, opt: true },
]);
/**
 * @generated from message scalekit.v1.directories.ListDirectoryUsersResponse
 */
class ListDirectoryUsersResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.directories.DirectoryUser users = 1;
         */
        this.users = [];
        /**
         * @generated from field: uint32 total_size = 2;
         */
        this.totalSize = 0;
        /**
         * @generated from field: string next_page_token = 3;
         */
        this.nextPageToken = "";
        /**
         * @generated from field: string prev_page_token = 4;
         */
        this.prevPageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListDirectoryUsersResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListDirectoryUsersResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListDirectoryUsersResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListDirectoryUsersResponse, a, b);
    }
}
exports.ListDirectoryUsersResponse = ListDirectoryUsersResponse;
ListDirectoryUsersResponse.runtime = protobuf_1.proto3;
ListDirectoryUsersResponse.typeName = "scalekit.v1.directories.ListDirectoryUsersResponse";
ListDirectoryUsersResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: DirectoryUser, repeated: true },
    { no: 2, name: "total_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "prev_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.ListDirectoryGroupsRequest
 */
class ListDirectoryGroupsRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string directory_id = 2;
         */
        this.directoryId = "";
        /**
         * @generated from field: uint32 page_size = 3;
         */
        this.pageSize = 0;
        /**
         * @generated from field: string page_token = 4;
         */
        this.pageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListDirectoryGroupsRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListDirectoryGroupsRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListDirectoryGroupsRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListDirectoryGroupsRequest, a, b);
    }
}
exports.ListDirectoryGroupsRequest = ListDirectoryGroupsRequest;
ListDirectoryGroupsRequest.runtime = protobuf_1.proto3;
ListDirectoryGroupsRequest.typeName = "scalekit.v1.directories.ListDirectoryGroupsRequest";
ListDirectoryGroupsRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "directory_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "updated_after", kind: "message", T: protobuf_1.Timestamp, opt: true },
    { no: 6, name: "include_detail", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "include_external_groups", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
]);
/**
 * @generated from message scalekit.v1.directories.ListDirectoryGroupsResponse
 */
class ListDirectoryGroupsResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.directories.DirectoryGroup groups = 1;
         */
        this.groups = [];
        /**
         * @generated from field: uint32 total_size = 2;
         */
        this.totalSize = 0;
        /**
         * @generated from field: string next_page_token = 3;
         */
        this.nextPageToken = "";
        /**
         * @generated from field: string prev_page_token = 4;
         */
        this.prevPageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListDirectoryGroupsResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListDirectoryGroupsResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListDirectoryGroupsResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListDirectoryGroupsResponse, a, b);
    }
}
exports.ListDirectoryGroupsResponse = ListDirectoryGroupsResponse;
ListDirectoryGroupsResponse.runtime = protobuf_1.proto3;
ListDirectoryGroupsResponse.typeName = "scalekit.v1.directories.ListDirectoryGroupsResponse";
ListDirectoryGroupsResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "groups", kind: "message", T: DirectoryGroup, repeated: true },
    { no: 2, name: "total_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "prev_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.ListDirectoryGroupsSummaryRequest
 */
class ListDirectoryGroupsSummaryRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string directory_id = 2;
         */
        this.directoryId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListDirectoryGroupsSummaryRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListDirectoryGroupsSummaryRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListDirectoryGroupsSummaryRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListDirectoryGroupsSummaryRequest, a, b);
    }
}
exports.ListDirectoryGroupsSummaryRequest = ListDirectoryGroupsSummaryRequest;
ListDirectoryGroupsSummaryRequest.runtime = protobuf_1.proto3;
ListDirectoryGroupsSummaryRequest.typeName = "scalekit.v1.directories.ListDirectoryGroupsSummaryRequest";
ListDirectoryGroupsSummaryRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "directory_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.Directory
 */
class Directory extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string name = 2;
         */
        this.name = "";
        /**
         * @generated from field: scalekit.v1.directories.DirectoryType directory_type = 3;
         */
        this.directoryType = DirectoryType.DIRECTORY_TYPE_UNSPECIFIED;
        /**
         * @generated from field: string organization_id = 4;
         */
        this.organizationId = "";
        /**
         * @generated from field: bool enabled = 5;
         */
        this.enabled = false;
        /**
         * @generated from field: scalekit.v1.directories.DirectoryProvider directory_provider = 6;
         */
        this.directoryProvider = DirectoryProvider.DIRECTORY_PROVIDER_UNSPECIFIED;
        /**
         * @generated from field: string directory_endpoint = 8;
         */
        this.directoryEndpoint = "";
        /**
         * @generated from field: int32 total_users = 9;
         */
        this.totalUsers = 0;
        /**
         * @generated from field: int32 total_groups = 10;
         */
        this.totalGroups = 0;
        /**
         * @generated from field: repeated scalekit.v1.directories.Secret secrets = 11;
         */
        this.secrets = [];
        /**
         * @generated from field: string status = 15;
         */
        this.status = "";
        /**
         * @generated from field: string email = 16;
         */
        this.email = "";
        /**
         * @generated from field: string groups_tracked = 17;
         */
        this.groupsTracked = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Directory().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Directory().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Directory().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Directory, a, b);
    }
}
exports.Directory = Directory;
Directory.runtime = protobuf_1.proto3;
Directory.typeName = "scalekit.v1.directories.Directory";
Directory.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "directory_type", kind: "enum", T: protobuf_1.proto3.getEnumType(DirectoryType) },
    { no: 4, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "directory_provider", kind: "enum", T: protobuf_1.proto3.getEnumType(DirectoryProvider) },
    { no: 7, name: "last_synced_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 8, name: "directory_endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "total_users", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "total_groups", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "secrets", kind: "message", T: Secret, repeated: true },
    { no: 12, name: "stats", kind: "message", T: Stats },
    { no: 13, name: "role_assignments", kind: "message", T: RoleAssignments },
    { no: 14, name: "attribute_mappings", kind: "message", T: AttributeMappings },
    { no: 15, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "groups_tracked", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.ToggleDirectoryRequest
 */
class ToggleDirectoryRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string id = 3;
         */
        this.id = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ToggleDirectoryRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ToggleDirectoryRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ToggleDirectoryRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ToggleDirectoryRequest, a, b);
    }
}
exports.ToggleDirectoryRequest = ToggleDirectoryRequest;
ToggleDirectoryRequest.runtime = protobuf_1.proto3;
ToggleDirectoryRequest.typeName = "scalekit.v1.directories.ToggleDirectoryRequest";
ToggleDirectoryRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.ToggleDirectoryResponse
 */
class ToggleDirectoryResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: bool enabled = 1;
         */
        this.enabled = false;
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ToggleDirectoryResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ToggleDirectoryResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ToggleDirectoryResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ToggleDirectoryResponse, a, b);
    }
}
exports.ToggleDirectoryResponse = ToggleDirectoryResponse;
ToggleDirectoryResponse.runtime = protobuf_1.proto3;
ToggleDirectoryResponse.typeName = "scalekit.v1.directories.ToggleDirectoryResponse";
ToggleDirectoryResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "error_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
]);
/**
 * @generated from message scalekit.v1.directories.DirectoryMapping
 */
class DirectoryMapping extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string key = 1;
         */
        this.key = "";
        /**
         * @generated from field: string map_to = 2;
         */
        this.mapTo = "";
        /**
         * @generated from field: string display_name = 3;
         */
        this.displayName = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DirectoryMapping().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DirectoryMapping().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DirectoryMapping().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DirectoryMapping, a, b);
    }
}
exports.DirectoryMapping = DirectoryMapping;
DirectoryMapping.runtime = protobuf_1.proto3;
DirectoryMapping.typeName = "scalekit.v1.directories.DirectoryMapping";
DirectoryMapping.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "map_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.DirectoryUser
 */
class DirectoryUser extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string email = 2;
         */
        this.email = "";
        /**
         * @generated from field: string preferred_username = 3;
         */
        this.preferredUsername = "";
        /**
         * @generated from field: string given_name = 4;
         */
        this.givenName = "";
        /**
         * @generated from field: string family_name = 5;
         */
        this.familyName = "";
        /**
         * @generated from field: repeated string emails = 16;
         */
        this.emails = [];
        /**
         * @generated from field: repeated scalekit.v1.directories.DirectoryGroup groups = 17;
         */
        this.groups = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DirectoryUser().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DirectoryUser().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DirectoryUser().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DirectoryUser, a, b);
    }
}
exports.DirectoryUser = DirectoryUser;
DirectoryUser.runtime = protobuf_1.proto3;
DirectoryUser.typeName = "scalekit.v1.directories.DirectoryUser";
DirectoryUser.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "preferred_username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "given_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "family_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "updated_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 16, name: "emails", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 17, name: "groups", kind: "message", T: DirectoryGroup, repeated: true },
    { no: 18, name: "user_detail", kind: "message", T: protobuf_1.Struct },
]);
/**
 * @generated from message scalekit.v1.directories.ExternalGroup
 */
class ExternalGroup extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string external_id = 1;
         */
        this.externalId = "";
        /**
         * @generated from field: string display_name = 2;
         */
        this.displayName = "";
        /**
         * @generated from field: string email = 3;
         */
        this.email = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ExternalGroup().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ExternalGroup().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ExternalGroup().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ExternalGroup, a, b);
    }
}
exports.ExternalGroup = ExternalGroup;
ExternalGroup.runtime = protobuf_1.proto3;
ExternalGroup.typeName = "scalekit.v1.directories.ExternalGroup";
ExternalGroup.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.DirectoryGroup
 */
class DirectoryGroup extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string display_name = 2;
         */
        this.displayName = "";
        /**
         * @generated from field: int32 total_users = 3;
         */
        this.totalUsers = 0;
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DirectoryGroup().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DirectoryGroup().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DirectoryGroup().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DirectoryGroup, a, b);
    }
}
exports.DirectoryGroup = DirectoryGroup;
DirectoryGroup.runtime = protobuf_1.proto3;
DirectoryGroup.typeName = "scalekit.v1.directories.DirectoryGroup";
DirectoryGroup.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "total_users", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "updated_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 5, name: "group_detail", kind: "message", T: protobuf_1.Struct },
]);
/**
 * @generated from message scalekit.v1.directories.CreateDirectorySecretRequest
 */
class CreateDirectorySecretRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string directory_id = 2;
         */
        this.directoryId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateDirectorySecretRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateDirectorySecretRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateDirectorySecretRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateDirectorySecretRequest, a, b);
    }
}
exports.CreateDirectorySecretRequest = CreateDirectorySecretRequest;
CreateDirectorySecretRequest.runtime = protobuf_1.proto3;
CreateDirectorySecretRequest.typeName = "scalekit.v1.directories.CreateDirectorySecretRequest";
CreateDirectorySecretRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "directory_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.CreateDirectorySecretResponse
 */
class CreateDirectorySecretResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string plain_secret = 1;
         */
        this.plainSecret = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateDirectorySecretResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateDirectorySecretResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateDirectorySecretResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateDirectorySecretResponse, a, b);
    }
}
exports.CreateDirectorySecretResponse = CreateDirectorySecretResponse;
CreateDirectorySecretResponse.runtime = protobuf_1.proto3;
CreateDirectorySecretResponse.typeName = "scalekit.v1.directories.CreateDirectorySecretResponse";
CreateDirectorySecretResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "plain_secret", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "secret", kind: "message", T: Secret },
]);
/**
 * @generated from message scalekit.v1.directories.RegenerateDirectorySecretRequest
 */
class RegenerateDirectorySecretRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string directory_id = 2;
         */
        this.directoryId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new RegenerateDirectorySecretRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RegenerateDirectorySecretRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RegenerateDirectorySecretRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RegenerateDirectorySecretRequest, a, b);
    }
}
exports.RegenerateDirectorySecretRequest = RegenerateDirectorySecretRequest;
RegenerateDirectorySecretRequest.runtime = protobuf_1.proto3;
RegenerateDirectorySecretRequest.typeName = "scalekit.v1.directories.RegenerateDirectorySecretRequest";
RegenerateDirectorySecretRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "directory_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.RegenerateDirectorySecretResponse
 */
class RegenerateDirectorySecretResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string plain_secret = 1;
         */
        this.plainSecret = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new RegenerateDirectorySecretResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RegenerateDirectorySecretResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RegenerateDirectorySecretResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RegenerateDirectorySecretResponse, a, b);
    }
}
exports.RegenerateDirectorySecretResponse = RegenerateDirectorySecretResponse;
RegenerateDirectorySecretResponse.runtime = protobuf_1.proto3;
RegenerateDirectorySecretResponse.typeName = "scalekit.v1.directories.RegenerateDirectorySecretResponse";
RegenerateDirectorySecretResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "plain_secret", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "secret", kind: "message", T: Secret },
]);
/**
 * @generated from message scalekit.v1.directories.Secret
 */
class Secret extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string secret_suffix = 4;
         */
        this.secretSuffix = "";
        /**
         * @generated from field: scalekit.v1.directories.SecretStatus status = 5;
         */
        this.status = SecretStatus.ACTIVE;
        /**
         * @generated from field: string directory_id = 9;
         */
        this.directoryId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Secret().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Secret().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Secret().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Secret, a, b);
    }
}
exports.Secret = Secret;
Secret.runtime = protobuf_1.proto3;
Secret.typeName = "scalekit.v1.directories.Secret";
Secret.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "create_time", kind: "message", T: protobuf_1.Timestamp },
    { no: 4, name: "secret_suffix", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "status", kind: "enum", T: protobuf_1.proto3.getEnumType(SecretStatus) },
    { no: 6, name: "expire_time", kind: "message", T: protobuf_1.Timestamp },
    { no: 7, name: "last_used_time", kind: "message", T: protobuf_1.Timestamp },
    { no: 9, name: "directory_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.Stats
 */
class Stats extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: int32 total_users = 1;
         */
        this.totalUsers = 0;
        /**
         * @generated from field: int32 total_groups = 2;
         */
        this.totalGroups = 0;
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Stats().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Stats().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Stats().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Stats, a, b);
    }
}
exports.Stats = Stats;
Stats.runtime = protobuf_1.proto3;
Stats.typeName = "scalekit.v1.directories.Stats";
Stats.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "total_users", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "total_groups", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "group_updated_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 4, name: "user_updated_at", kind: "message", T: protobuf_1.Timestamp },
]);
/**
 * @generated from message scalekit.v1.directories.AssignRolesRequest
 */
class AssignRolesRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string id = 2;
         */
        this.id = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AssignRolesRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AssignRolesRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AssignRolesRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AssignRolesRequest, a, b);
    }
}
exports.AssignRolesRequest = AssignRolesRequest;
AssignRolesRequest.runtime = protobuf_1.proto3;
AssignRolesRequest.typeName = "scalekit.v1.directories.AssignRolesRequest";
AssignRolesRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "role_assignments", kind: "message", T: RoleAssignments },
]);
/**
 * @generated from message scalekit.v1.directories.RoleAssignments
 */
class RoleAssignments extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.directories.RoleAssignment assignments = 1;
         */
        this.assignments = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new RoleAssignments().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RoleAssignments().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RoleAssignments().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RoleAssignments, a, b);
    }
}
exports.RoleAssignments = RoleAssignments;
RoleAssignments.runtime = protobuf_1.proto3;
RoleAssignments.typeName = "scalekit.v1.directories.RoleAssignments";
RoleAssignments.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "assignments", kind: "message", T: RoleAssignment, repeated: true },
]);
/**
 * @generated from message scalekit.v1.directories.AssignRolesResponse
 */
class AssignRolesResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AssignRolesResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AssignRolesResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AssignRolesResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AssignRolesResponse, a, b);
    }
}
exports.AssignRolesResponse = AssignRolesResponse;
AssignRolesResponse.runtime = protobuf_1.proto3;
AssignRolesResponse.typeName = "scalekit.v1.directories.AssignRolesResponse";
AssignRolesResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "role_assignments", kind: "message", T: RoleAssignments },
]);
/**
 * @generated from message scalekit.v1.directories.RoleAssignment
 */
class RoleAssignment extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string group_id = 1;
         */
        this.groupId = "";
        /**
         * @generated from field: string role_name = 2;
         */
        this.roleName = "";
        /**
         * @generated from field: string role_id = 3;
         */
        this.roleId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new RoleAssignment().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RoleAssignment().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RoleAssignment().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RoleAssignment, a, b);
    }
}
exports.RoleAssignment = RoleAssignment;
RoleAssignment.runtime = protobuf_1.proto3;
RoleAssignment.typeName = "scalekit.v1.directories.RoleAssignment";
RoleAssignment.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "role_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.UpdateAttributesRequest
 */
class UpdateAttributesRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string id = 2;
         */
        this.id = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateAttributesRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateAttributesRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateAttributesRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateAttributesRequest, a, b);
    }
}
exports.UpdateAttributesRequest = UpdateAttributesRequest;
UpdateAttributesRequest.runtime = protobuf_1.proto3;
UpdateAttributesRequest.typeName = "scalekit.v1.directories.UpdateAttributesRequest";
UpdateAttributesRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "attribute_mapping", kind: "message", T: AttributeMappings },
]);
/**
 * @generated from message scalekit.v1.directories.AttributeMappings
 */
class AttributeMappings extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.directories.AttributeMapping attributes = 1;
         */
        this.attributes = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AttributeMappings().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AttributeMappings().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AttributeMappings().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AttributeMappings, a, b);
    }
}
exports.AttributeMappings = AttributeMappings;
AttributeMappings.runtime = protobuf_1.proto3;
AttributeMappings.typeName = "scalekit.v1.directories.AttributeMappings";
AttributeMappings.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "attributes", kind: "message", T: AttributeMapping, repeated: true },
]);
/**
 * @generated from message scalekit.v1.directories.AttributeMapping
 */
class AttributeMapping extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string key = 1;
         */
        this.key = "";
        /**
         * @generated from field: string map_to = 2;
         */
        this.mapTo = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AttributeMapping().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AttributeMapping().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AttributeMapping().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AttributeMapping, a, b);
    }
}
exports.AttributeMapping = AttributeMapping;
AttributeMapping.runtime = protobuf_1.proto3;
AttributeMapping.typeName = "scalekit.v1.directories.AttributeMapping";
AttributeMapping.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "map_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.UpdateAttributesResponse
 */
class UpdateAttributesResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateAttributesResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateAttributesResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateAttributesResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateAttributesResponse, a, b);
    }
}
exports.UpdateAttributesResponse = UpdateAttributesResponse;
UpdateAttributesResponse.runtime = protobuf_1.proto3;
UpdateAttributesResponse.typeName = "scalekit.v1.directories.UpdateAttributesResponse";
UpdateAttributesResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "attribute_mappings", kind: "message", T: AttributeMappings },
]);
/**
 * @generated from message scalekit.v1.directories.DeleteDirectoryRequest
 */
class DeleteDirectoryRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string id = 3;
         */
        this.id = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DeleteDirectoryRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeleteDirectoryRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeleteDirectoryRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeleteDirectoryRequest, a, b);
    }
}
exports.DeleteDirectoryRequest = DeleteDirectoryRequest;
DeleteDirectoryRequest.runtime = protobuf_1.proto3;
DeleteDirectoryRequest.typeName = "scalekit.v1.directories.DeleteDirectoryRequest";
DeleteDirectoryRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.directories.TriggerDirectorySyncRequest
 */
class TriggerDirectorySyncRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string directory_id = 1;
         */
        this.directoryId = "";
        /**
         * @generated from field: string organization_id = 2;
         */
        this.organizationId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new TriggerDirectorySyncRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new TriggerDirectorySyncRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new TriggerDirectorySyncRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(TriggerDirectorySyncRequest, a, b);
    }
}
exports.TriggerDirectorySyncRequest = TriggerDirectorySyncRequest;
TriggerDirectorySyncRequest.runtime = protobuf_1.proto3;
TriggerDirectorySyncRequest.typeName = "scalekit.v1.directories.TriggerDirectorySyncRequest";
TriggerDirectorySyncRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "directory_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
//# sourceMappingURL=directories_pb.js.map