// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file scalekit/v1/connected_accounts/connected_accounts.proto (package scalekit.v1.connected_accounts, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateConnectedAccountRequest, CreateConnectedAccountResponse, DeleteConnectedAccountRequest, DeleteConnectedAccountResponse, GetConnectedAccountByIdentifierRequest, GetConnectedAccountByIdentifierResponse, GetMagicLinkForConnectedAccountRequest, GetMagicLinkForConnectedAccountResponse, ListConnectedAccountsRequest, ListConnectedAccountsResponse, SearchConnectedAccountsRequest, SearchConnectedAccountsResponse, UpdateConnectedAccountRequest, UpdateConnectedAccountResponse } from "./connected_accounts_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scalekit.v1.connected_accounts.ConnectedAccountService
 */
export const ConnectedAccountService = {
  typeName: "scalekit.v1.connected_accounts.ConnectedAccountService",
  methods: {
    /**
     * List Connected Accounts
     *
     * @generated from rpc scalekit.v1.connected_accounts.ConnectedAccountService.ListConnectedAccounts
     */
    listConnectedAccounts: {
      name: "ListConnectedAccounts",
      I: ListConnectedAccountsRequest,
      O: ListConnectedAccountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Search Connected Accounts
     *
     * @generated from rpc scalekit.v1.connected_accounts.ConnectedAccountService.SearchConnectedAccounts
     */
    searchConnectedAccounts: {
      name: "SearchConnectedAccounts",
      I: SearchConnectedAccountsRequest,
      O: SearchConnectedAccountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Create Connected Account
     *
     * @generated from rpc scalekit.v1.connected_accounts.ConnectedAccountService.CreateConnectedAccount
     */
    createConnectedAccount: {
      name: "CreateConnectedAccount",
      I: CreateConnectedAccountRequest,
      O: CreateConnectedAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update Connected Account
     *
     * @generated from rpc scalekit.v1.connected_accounts.ConnectedAccountService.UpdateConnectedAccount
     */
    updateConnectedAccount: {
      name: "UpdateConnectedAccount",
      I: UpdateConnectedAccountRequest,
      O: UpdateConnectedAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete Connected Account
     *
     * @generated from rpc scalekit.v1.connected_accounts.ConnectedAccountService.DeleteConnectedAccount
     */
    deleteConnectedAccount: {
      name: "DeleteConnectedAccount",
      I: DeleteConnectedAccountRequest,
      O: DeleteConnectedAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Generate Magic Link for Account Connection
     *
     * @generated from rpc scalekit.v1.connected_accounts.ConnectedAccountService.GetMagicLinkForConnectedAccount
     */
    getMagicLinkForConnectedAccount: {
      name: "GetMagicLinkForConnectedAccount",
      I: GetMagicLinkForConnectedAccountRequest,
      O: GetMagicLinkForConnectedAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get Connected Account Authentication Details
     *
     * @generated from rpc scalekit.v1.connected_accounts.ConnectedAccountService.GetConnectedAccountAuth
     */
    getConnectedAccountAuth: {
      name: "GetConnectedAccountAuth",
      I: GetConnectedAccountByIdentifierRequest,
      O: GetConnectedAccountByIdentifierResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

