"use strict";
// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file scalekit/v1/commons/commons.proto (package scalekit.v1.commons, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegionCode = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from enum scalekit.v1.commons.RegionCode
 */
var RegionCode;
(function (RegionCode) {
    /**
     *
     * If the region code is unspecified the selected region will automatically be decided based on the origin of the call.
     *
     * @generated from enum value: REGION_CODE_UNSPECIFIED = 0;
     */
    RegionCode[RegionCode["REGION_CODE_UNSPECIFIED"] = 0] = "REGION_CODE_UNSPECIFIED";
    /**
     * @generated from enum value: US = 1;
     */
    RegionCode[RegionCode["US"] = 1] = "US";
    /**
     * @generated from enum value: EU = 2;
     */
    RegionCode[RegionCode["EU"] = 2] = "EU";
})(RegionCode || (exports.RegionCode = RegionCode = {}));
// Retrieve enum metadata with: proto3.getEnumType(RegionCode)
protobuf_1.proto3.util.setEnumType(RegionCode, "scalekit.v1.commons.RegionCode", [
    { no: 0, name: "REGION_CODE_UNSPECIFIED" },
    { no: 1, name: "US" },
    { no: 2, name: "EU" },
]);
//# sourceMappingURL=commons_pb.js.map