"use strict";
// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file scalekit/v1/users/users.proto (package scalekit.v1.users, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListUserPermissionsResponse = exports.Permission = exports.ListUserPermissionsRequest = exports.RemoveUserRoleRequest = exports.AssignUserRolesResponse = exports.AssignRoleRequest = exports.AssignUserRolesRequest = exports.ListUserRolesResponse = exports.ListUserRolesRequest = exports.ResendInviteResponse = exports.ResendInviteRequest = exports.Invite = exports.UpdateUserProfile = exports.CreateUserProfile = exports.CreateUser = exports.SearchOrganizationUsersResponse = exports.SearchOrganizationUsersRequest = exports.UpdateMembershipResponse = exports.CreateMembership = exports.UpdateMembership = exports.UpdateMembershipRequest = exports.DeleteUserRequest = exports.SearchUsersResponse = exports.SearchUsersRequest = exports.ListUsersResponse = exports.ListUsersRequest = exports.CreateMembershipResponse = exports.CreateMembershipRequest = exports.DeleteMembershipRequest = exports.ListOrganizationUsersResponse = exports.ListOrganizationUsersRequest = exports.GetUserResponse = exports.GetUserRequest = exports.UpdateUserResponse = exports.UpdateUserRequest = exports.UpdateUser = exports.CreateUserAndMembershipResponse = exports.CreateUserAndMembershipRequest = exports.User = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
const commons_pb_js_1 = require("../commons/commons_pb.js");
/**
 * @generated from message scalekit.v1.users.User
 */
class User extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string environment_id = 2;
         */
        this.environmentId = "";
        /**
         * @generated from field: string email = 5;
         */
        this.email = "";
        /**
         * @generated from field: repeated scalekit.v1.commons.OrganizationMembership memberships = 7;
         */
        this.memberships = [];
        /**
         * @generated from field: map<string, string> metadata = 9;
         */
        this.metadata = {};
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new User().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new User().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new User().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(User, a, b);
    }
}
exports.User = User;
User.runtime = protobuf_1.proto3;
User.typeName = "scalekit.v1.users.User";
User.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "environment_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "create_time", kind: "message", T: protobuf_1.Timestamp },
    { no: 4, name: "update_time", kind: "message", T: protobuf_1.Timestamp },
    { no: 5, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "memberships", kind: "message", T: commons_pb_js_1.OrganizationMembership, repeated: true },
    { no: 8, name: "user_profile", kind: "message", T: commons_pb_js_1.UserProfile },
    { no: 9, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
    { no: 10, name: "last_login_time", kind: "message", T: protobuf_1.Timestamp },
]);
/**
 * @generated from message scalekit.v1.users.CreateUserAndMembershipRequest
 */
class CreateUserAndMembershipRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateUserAndMembershipRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateUserAndMembershipRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateUserAndMembershipRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateUserAndMembershipRequest, a, b);
    }
}
exports.CreateUserAndMembershipRequest = CreateUserAndMembershipRequest;
CreateUserAndMembershipRequest.runtime = protobuf_1.proto3;
CreateUserAndMembershipRequest.typeName = "scalekit.v1.users.CreateUserAndMembershipRequest";
CreateUserAndMembershipRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user", kind: "message", T: CreateUser },
    { no: 3, name: "send_invitation_email", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
]);
/**
 * @generated from message scalekit.v1.users.CreateUserAndMembershipResponse
 */
class CreateUserAndMembershipResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateUserAndMembershipResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateUserAndMembershipResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateUserAndMembershipResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateUserAndMembershipResponse, a, b);
    }
}
exports.CreateUserAndMembershipResponse = CreateUserAndMembershipResponse;
CreateUserAndMembershipResponse.runtime = protobuf_1.proto3;
CreateUserAndMembershipResponse.typeName = "scalekit.v1.users.CreateUserAndMembershipResponse";
CreateUserAndMembershipResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
]);
/**
 * @generated from message scalekit.v1.users.UpdateUser
 */
class UpdateUser extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: map<string, string> metadata = 9;
         */
        this.metadata = {};
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateUser().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateUser().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateUser().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateUser, a, b);
    }
}
exports.UpdateUser = UpdateUser;
UpdateUser.runtime = protobuf_1.proto3;
UpdateUser.typeName = "scalekit.v1.users.UpdateUser";
UpdateUser.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 6, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "user_profile", kind: "message", T: UpdateUserProfile },
    { no: 9, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
]);
/**
 * @generated from message scalekit.v1.users.UpdateUserRequest
 */
class UpdateUserRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from oneof scalekit.v1.users.UpdateUserRequest.identities
         */
        this.identities = { case: undefined };
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateUserRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateUserRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateUserRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateUserRequest, a, b);
    }
}
exports.UpdateUserRequest = UpdateUserRequest;
UpdateUserRequest.runtime = protobuf_1.proto3;
UpdateUserRequest.typeName = "scalekit.v1.users.UpdateUserRequest";
UpdateUserRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 2, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 3, name: "user", kind: "message", T: UpdateUser },
]);
/**
 * @generated from message scalekit.v1.users.UpdateUserResponse
 */
class UpdateUserResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateUserResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateUserResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateUserResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateUserResponse, a, b);
    }
}
exports.UpdateUserResponse = UpdateUserResponse;
UpdateUserResponse.runtime = protobuf_1.proto3;
UpdateUserResponse.typeName = "scalekit.v1.users.UpdateUserResponse";
UpdateUserResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
]);
/**
 * @generated from message scalekit.v1.users.GetUserRequest
 */
class GetUserRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from oneof scalekit.v1.users.GetUserRequest.identities
         */
        this.identities = { case: undefined };
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GetUserRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetUserRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetUserRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetUserRequest, a, b);
    }
}
exports.GetUserRequest = GetUserRequest;
GetUserRequest.runtime = protobuf_1.proto3;
GetUserRequest.typeName = "scalekit.v1.users.GetUserRequest";
GetUserRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 2, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
]);
/**
 * @generated from message scalekit.v1.users.GetUserResponse
 */
class GetUserResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new GetUserResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetUserResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetUserResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetUserResponse, a, b);
    }
}
exports.GetUserResponse = GetUserResponse;
GetUserResponse.runtime = protobuf_1.proto3;
GetUserResponse.typeName = "scalekit.v1.users.GetUserResponse";
GetUserResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
]);
/**
 * @generated from message scalekit.v1.users.ListOrganizationUsersRequest
 */
class ListOrganizationUsersRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: uint32 page_size = 2;
         */
        this.pageSize = 0;
        /**
         * @generated from field: string page_token = 3;
         */
        this.pageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListOrganizationUsersRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListOrganizationUsersRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListOrganizationUsersRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListOrganizationUsersRequest, a, b);
    }
}
exports.ListOrganizationUsersRequest = ListOrganizationUsersRequest;
ListOrganizationUsersRequest.runtime = protobuf_1.proto3;
ListOrganizationUsersRequest.typeName = "scalekit.v1.users.ListOrganizationUsersRequest";
ListOrganizationUsersRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.ListOrganizationUsersResponse
 */
class ListOrganizationUsersResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string next_page_token = 1;
         */
        this.nextPageToken = "";
        /**
         * @generated from field: uint32 total_size = 2;
         */
        this.totalSize = 0;
        /**
         * @generated from field: repeated scalekit.v1.users.User users = 3;
         */
        this.users = [];
        /**
         * @generated from field: string prev_page_token = 4;
         */
        this.prevPageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListOrganizationUsersResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListOrganizationUsersResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListOrganizationUsersResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListOrganizationUsersResponse, a, b);
    }
}
exports.ListOrganizationUsersResponse = ListOrganizationUsersResponse;
ListOrganizationUsersResponse.runtime = protobuf_1.proto3;
ListOrganizationUsersResponse.typeName = "scalekit.v1.users.ListOrganizationUsersResponse";
ListOrganizationUsersResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "total_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "users", kind: "message", T: User, repeated: true },
    { no: 4, name: "prev_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.DeleteMembershipRequest
 */
class DeleteMembershipRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from oneof scalekit.v1.users.DeleteMembershipRequest.identities
         */
        this.identities = { case: undefined };
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DeleteMembershipRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeleteMembershipRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeleteMembershipRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeleteMembershipRequest, a, b);
    }
}
exports.DeleteMembershipRequest = DeleteMembershipRequest;
DeleteMembershipRequest.runtime = protobuf_1.proto3;
DeleteMembershipRequest.typeName = "scalekit.v1.users.DeleteMembershipRequest";
DeleteMembershipRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 3, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 5, name: "cascade", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
]);
/**
 * @generated from message scalekit.v1.users.CreateMembershipRequest
 */
class CreateMembershipRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from oneof scalekit.v1.users.CreateMembershipRequest.identities
         */
        this.identities = { case: undefined };
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateMembershipRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateMembershipRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateMembershipRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateMembershipRequest, a, b);
    }
}
exports.CreateMembershipRequest = CreateMembershipRequest;
CreateMembershipRequest.runtime = protobuf_1.proto3;
CreateMembershipRequest.typeName = "scalekit.v1.users.CreateMembershipRequest";
CreateMembershipRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "membership", kind: "message", T: CreateMembership },
    { no: 3, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 4, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 5, name: "send_invitation_email", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
]);
/**
 * @generated from message scalekit.v1.users.CreateMembershipResponse
 */
class CreateMembershipResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateMembershipResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateMembershipResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateMembershipResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateMembershipResponse, a, b);
    }
}
exports.CreateMembershipResponse = CreateMembershipResponse;
CreateMembershipResponse.runtime = protobuf_1.proto3;
CreateMembershipResponse.typeName = "scalekit.v1.users.CreateMembershipResponse";
CreateMembershipResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
]);
/**
 * @generated from message scalekit.v1.users.ListUsersRequest
 */
class ListUsersRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: uint32 page_size = 1;
         */
        this.pageSize = 0;
        /**
         * @generated from field: string page_token = 2;
         */
        this.pageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListUsersRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListUsersRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListUsersRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListUsersRequest, a, b);
    }
}
exports.ListUsersRequest = ListUsersRequest;
ListUsersRequest.runtime = protobuf_1.proto3;
ListUsersRequest.typeName = "scalekit.v1.users.ListUsersRequest";
ListUsersRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.ListUsersResponse
 */
class ListUsersResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.users.User users = 1;
         */
        this.users = [];
        /**
         * @generated from field: string next_page_token = 2;
         */
        this.nextPageToken = "";
        /**
         * @generated from field: uint32 total_size = 3;
         */
        this.totalSize = 0;
        /**
         * @generated from field: string prev_page_token = 4;
         */
        this.prevPageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListUsersResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListUsersResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListUsersResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListUsersResponse, a, b);
    }
}
exports.ListUsersResponse = ListUsersResponse;
ListUsersResponse.runtime = protobuf_1.proto3;
ListUsersResponse.typeName = "scalekit.v1.users.ListUsersResponse";
ListUsersResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: User, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "total_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "prev_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.SearchUsersRequest
 */
class SearchUsersRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string query = 1;
         */
        this.query = "";
        /**
         * @generated from field: uint32 page_size = 2;
         */
        this.pageSize = 0;
        /**
         * @generated from field: string page_token = 3;
         */
        this.pageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new SearchUsersRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SearchUsersRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SearchUsersRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SearchUsersRequest, a, b);
    }
}
exports.SearchUsersRequest = SearchUsersRequest;
SearchUsersRequest.runtime = protobuf_1.proto3;
SearchUsersRequest.typeName = "scalekit.v1.users.SearchUsersRequest";
SearchUsersRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.SearchUsersResponse
 */
class SearchUsersResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string next_page_token = 1;
         */
        this.nextPageToken = "";
        /**
         * @generated from field: uint32 total_size = 2;
         */
        this.totalSize = 0;
        /**
         * @generated from field: repeated scalekit.v1.users.User users = 3;
         */
        this.users = [];
        /**
         * @generated from field: string prev_page_token = 4;
         */
        this.prevPageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new SearchUsersResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SearchUsersResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SearchUsersResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SearchUsersResponse, a, b);
    }
}
exports.SearchUsersResponse = SearchUsersResponse;
SearchUsersResponse.runtime = protobuf_1.proto3;
SearchUsersResponse.typeName = "scalekit.v1.users.SearchUsersResponse";
SearchUsersResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "total_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "users", kind: "message", T: User, repeated: true },
    { no: 4, name: "prev_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.DeleteUserRequest
 */
class DeleteUserRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from oneof scalekit.v1.users.DeleteUserRequest.identities
         */
        this.identities = { case: undefined };
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new DeleteUserRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeleteUserRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeleteUserRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeleteUserRequest, a, b);
    }
}
exports.DeleteUserRequest = DeleteUserRequest;
DeleteUserRequest.runtime = protobuf_1.proto3;
DeleteUserRequest.typeName = "scalekit.v1.users.DeleteUserRequest";
DeleteUserRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 2, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
]);
/**
 * @generated from message scalekit.v1.users.UpdateMembershipRequest
 */
class UpdateMembershipRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from oneof scalekit.v1.users.UpdateMembershipRequest.identities
         */
        this.identities = { case: undefined };
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateMembershipRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateMembershipRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateMembershipRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateMembershipRequest, a, b);
    }
}
exports.UpdateMembershipRequest = UpdateMembershipRequest;
UpdateMembershipRequest.runtime = protobuf_1.proto3;
UpdateMembershipRequest.typeName = "scalekit.v1.users.UpdateMembershipRequest";
UpdateMembershipRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 3, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identities" },
    { no: 5, name: "membership", kind: "message", T: UpdateMembership },
]);
/**
 * @generated from message scalekit.v1.users.UpdateMembership
 */
class UpdateMembership extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.commons.Role roles = 4;
         */
        this.roles = [];
        /**
         * @generated from field: map<string, string> metadata = 7;
         */
        this.metadata = {};
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateMembership().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateMembership().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateMembership().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateMembership, a, b);
    }
}
exports.UpdateMembership = UpdateMembership;
UpdateMembership.runtime = protobuf_1.proto3;
UpdateMembership.typeName = "scalekit.v1.users.UpdateMembership";
UpdateMembership.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 4, name: "roles", kind: "message", T: commons_pb_js_1.Role, repeated: true },
    { no: 7, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
]);
/**
 * @generated from message scalekit.v1.users.CreateMembership
 */
class CreateMembership extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.commons.Role roles = 4;
         */
        this.roles = [];
        /**
         * @generated from field: map<string, string> metadata = 7;
         */
        this.metadata = {};
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateMembership().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateMembership().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateMembership().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateMembership, a, b);
    }
}
exports.CreateMembership = CreateMembership;
CreateMembership.runtime = protobuf_1.proto3;
CreateMembership.typeName = "scalekit.v1.users.CreateMembership";
CreateMembership.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 4, name: "roles", kind: "message", T: commons_pb_js_1.Role, repeated: true },
    { no: 7, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
    { no: 8, name: "inviter_email", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
]);
/**
 * @generated from message scalekit.v1.users.UpdateMembershipResponse
 */
class UpdateMembershipResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateMembershipResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateMembershipResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateMembershipResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateMembershipResponse, a, b);
    }
}
exports.UpdateMembershipResponse = UpdateMembershipResponse;
UpdateMembershipResponse.runtime = protobuf_1.proto3;
UpdateMembershipResponse.typeName = "scalekit.v1.users.UpdateMembershipResponse";
UpdateMembershipResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
]);
/**
 * @generated from message scalekit.v1.users.SearchOrganizationUsersRequest
 */
class SearchOrganizationUsersRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string query = 2;
         */
        this.query = "";
        /**
         * @generated from field: uint32 page_size = 3;
         */
        this.pageSize = 0;
        /**
         * @generated from field: string page_token = 4;
         */
        this.pageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new SearchOrganizationUsersRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SearchOrganizationUsersRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SearchOrganizationUsersRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SearchOrganizationUsersRequest, a, b);
    }
}
exports.SearchOrganizationUsersRequest = SearchOrganizationUsersRequest;
SearchOrganizationUsersRequest.runtime = protobuf_1.proto3;
SearchOrganizationUsersRequest.typeName = "scalekit.v1.users.SearchOrganizationUsersRequest";
SearchOrganizationUsersRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.SearchOrganizationUsersResponse
 */
class SearchOrganizationUsersResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string next_page_token = 1;
         */
        this.nextPageToken = "";
        /**
         * @generated from field: uint32 total_size = 2;
         */
        this.totalSize = 0;
        /**
         * @generated from field: repeated scalekit.v1.users.User users = 3;
         */
        this.users = [];
        /**
         * @generated from field: string prev_page_token = 4;
         */
        this.prevPageToken = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new SearchOrganizationUsersResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SearchOrganizationUsersResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SearchOrganizationUsersResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SearchOrganizationUsersResponse, a, b);
    }
}
exports.SearchOrganizationUsersResponse = SearchOrganizationUsersResponse;
SearchOrganizationUsersResponse.runtime = protobuf_1.proto3;
SearchOrganizationUsersResponse.typeName = "scalekit.v1.users.SearchOrganizationUsersResponse";
SearchOrganizationUsersResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "total_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "users", kind: "message", T: User, repeated: true },
    { no: 4, name: "prev_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.CreateUser
 */
class CreateUser extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string email = 5;
         */
        this.email = "";
        /**
         * @generated from field: map<string, string> metadata = 9;
         */
        this.metadata = {};
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateUser().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateUser().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateUser().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateUser, a, b);
    }
}
exports.CreateUser = CreateUser;
CreateUser.runtime = protobuf_1.proto3;
CreateUser.typeName = "scalekit.v1.users.CreateUser";
CreateUser.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 5, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "external_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "membership", kind: "message", T: CreateMembership },
    { no: 8, name: "user_profile", kind: "message", T: CreateUserProfile },
    { no: 9, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
]);
/**
 * @generated from message scalekit.v1.users.CreateUserProfile
 */
class CreateUserProfile extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string given_name = 2;
         */
        this.givenName = "";
        /**
         * @generated from field: string family_name = 3;
         */
        this.familyName = "";
        /**
         * @generated from field: string name = 4;
         */
        this.name = "";
        /**
         * @generated from field: string locale = 5;
         */
        this.locale = "";
        /**
         * @generated from field: string phone_number = 7;
         */
        this.phoneNumber = "";
        /**
         * @generated from field: map<string, string> metadata = 8;
         */
        this.metadata = {};
        /**
         * @generated from field: map<string, string> custom_attributes = 9;
         */
        this.customAttributes = {};
        /**
         * @generated from field: string preferred_username = 10;
         */
        this.preferredUsername = "";
        /**
         * @generated from field: repeated string groups = 13;
         */
        this.groups = [];
        /**
         * @generated from field: string first_name = 21 [deprecated = true];
         * @deprecated
         */
        this.firstName = "";
        /**
         * @generated from field: string last_name = 22 [deprecated = true];
         * @deprecated
         */
        this.lastName = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new CreateUserProfile().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreateUserProfile().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreateUserProfile().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreateUserProfile, a, b);
    }
}
exports.CreateUserProfile = CreateUserProfile;
CreateUserProfile.runtime = protobuf_1.proto3;
CreateUserProfile.typeName = "scalekit.v1.users.CreateUserProfile";
CreateUserProfile.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 2, name: "given_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "family_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "locale", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "phone_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
    { no: 9, name: "custom_attributes", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
    { no: 10, name: "preferred_username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "picture", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 12, name: "gender", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 13, name: "groups", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 21, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 22, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.UpdateUserProfile
 */
class UpdateUserProfile extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: map<string, string> metadata = 8;
         */
        this.metadata = {};
        /**
         * @generated from field: map<string, string> custom_attributes = 9;
         */
        this.customAttributes = {};
        /**
         * @generated from field: repeated string groups = 13;
         */
        this.groups = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new UpdateUserProfile().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UpdateUserProfile().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UpdateUserProfile().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UpdateUserProfile, a, b);
    }
}
exports.UpdateUserProfile = UpdateUserProfile;
UpdateUserProfile.runtime = protobuf_1.proto3;
UpdateUserProfile.typeName = "scalekit.v1.users.UpdateUserProfile";
UpdateUserProfile.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 2, name: "given_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "family_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "locale", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "phone_number", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
    { no: 9, name: "custom_attributes", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
    { no: 21, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 22, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "preferred_username", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "picture", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 12, name: "gender", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 13, name: "groups", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
]);
/**
 * @generated from message scalekit.v1.users.Invite
 */
class Invite extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string user_id = 2;
         */
        this.userId = "";
        /**
         * @generated from field: string status = 4;
         */
        this.status = "";
        /**
         * @generated from field: int32 resent_count = 8;
         */
        this.resentCount = 0;
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Invite().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Invite().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Invite().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Invite, a, b);
    }
}
exports.Invite = Invite;
Invite.runtime = protobuf_1.proto3;
Invite.typeName = "scalekit.v1.users.Invite";
Invite.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "inviter_email", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "created_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 6, name: "expires_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 7, name: "resent_at", kind: "message", T: protobuf_1.Timestamp },
    { no: 8, name: "resent_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
]);
/**
 * @generated from message scalekit.v1.users.ResendInviteRequest
 */
class ResendInviteRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string id = 2;
         */
        this.id = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ResendInviteRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ResendInviteRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ResendInviteRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ResendInviteRequest, a, b);
    }
}
exports.ResendInviteRequest = ResendInviteRequest;
ResendInviteRequest.runtime = protobuf_1.proto3;
ResendInviteRequest.typeName = "scalekit.v1.users.ResendInviteRequest";
ResendInviteRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.ResendInviteResponse
 */
class ResendInviteResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ResendInviteResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ResendInviteResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ResendInviteResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ResendInviteResponse, a, b);
    }
}
exports.ResendInviteResponse = ResendInviteResponse;
ResendInviteResponse.runtime = protobuf_1.proto3;
ResendInviteResponse.typeName = "scalekit.v1.users.ResendInviteResponse";
ResendInviteResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "invite", kind: "message", T: Invite },
]);
/**
 * @generated from message scalekit.v1.users.ListUserRolesRequest
 */
class ListUserRolesRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string user_id = 2;
         */
        this.userId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListUserRolesRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListUserRolesRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListUserRolesRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListUserRolesRequest, a, b);
    }
}
exports.ListUserRolesRequest = ListUserRolesRequest;
ListUserRolesRequest.runtime = protobuf_1.proto3;
ListUserRolesRequest.typeName = "scalekit.v1.users.ListUserRolesRequest";
ListUserRolesRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.ListUserRolesResponse
 */
class ListUserRolesResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.commons.Role roles = 1;
         */
        this.roles = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListUserRolesResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListUserRolesResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListUserRolesResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListUserRolesResponse, a, b);
    }
}
exports.ListUserRolesResponse = ListUserRolesResponse;
ListUserRolesResponse.runtime = protobuf_1.proto3;
ListUserRolesResponse.typeName = "scalekit.v1.users.ListUserRolesResponse";
ListUserRolesResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "roles", kind: "message", T: commons_pb_js_1.Role, repeated: true },
]);
/**
 * @generated from message scalekit.v1.users.AssignUserRolesRequest
 */
class AssignUserRolesRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string user_id = 2;
         */
        this.userId = "";
        /**
         * @generated from field: repeated scalekit.v1.users.AssignRoleRequest roles = 3;
         */
        this.roles = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AssignUserRolesRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AssignUserRolesRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AssignUserRolesRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AssignUserRolesRequest, a, b);
    }
}
exports.AssignUserRolesRequest = AssignUserRolesRequest;
AssignUserRolesRequest.runtime = protobuf_1.proto3;
AssignUserRolesRequest.typeName = "scalekit.v1.users.AssignUserRolesRequest";
AssignUserRolesRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "roles", kind: "message", T: AssignRoleRequest, repeated: true },
]);
/**
 * @generated from message scalekit.v1.users.AssignRoleRequest
 */
class AssignRoleRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1 [deprecated = true];
         * @deprecated
         */
        this.id = "";
        /**
         * @generated from field: string role_name = 2;
         */
        this.roleName = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AssignRoleRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AssignRoleRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AssignRoleRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AssignRoleRequest, a, b);
    }
}
exports.AssignRoleRequest = AssignRoleRequest;
AssignRoleRequest.runtime = protobuf_1.proto3;
AssignRoleRequest.typeName = "scalekit.v1.users.AssignRoleRequest";
AssignRoleRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.AssignUserRolesResponse
 */
class AssignUserRolesResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.commons.Role roles = 1;
         */
        this.roles = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AssignUserRolesResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AssignUserRolesResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AssignUserRolesResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AssignUserRolesResponse, a, b);
    }
}
exports.AssignUserRolesResponse = AssignUserRolesResponse;
AssignUserRolesResponse.runtime = protobuf_1.proto3;
AssignUserRolesResponse.typeName = "scalekit.v1.users.AssignUserRolesResponse";
AssignUserRolesResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "roles", kind: "message", T: commons_pb_js_1.Role, repeated: true },
]);
/**
 * @generated from message scalekit.v1.users.RemoveUserRoleRequest
 */
class RemoveUserRoleRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string user_id = 2;
         */
        this.userId = "";
        /**
         * @generated from field: string role_name = 3;
         */
        this.roleName = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new RemoveUserRoleRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RemoveUserRoleRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RemoveUserRoleRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RemoveUserRoleRequest, a, b);
    }
}
exports.RemoveUserRoleRequest = RemoveUserRoleRequest;
RemoveUserRoleRequest.runtime = protobuf_1.proto3;
RemoveUserRoleRequest.typeName = "scalekit.v1.users.RemoveUserRoleRequest";
RemoveUserRoleRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.ListUserPermissionsRequest
 */
class ListUserPermissionsRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string user_id = 2;
         */
        this.userId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListUserPermissionsRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListUserPermissionsRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListUserPermissionsRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListUserPermissionsRequest, a, b);
    }
}
exports.ListUserPermissionsRequest = ListUserPermissionsRequest;
ListUserPermissionsRequest.runtime = protobuf_1.proto3;
ListUserPermissionsRequest.typeName = "scalekit.v1.users.ListUserPermissionsRequest";
ListUserPermissionsRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.users.Permission
 */
class Permission extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string id = 1;
         */
        this.id = "";
        /**
         * @generated from field: string name = 2;
         */
        this.name = "";
        /**
         * @generated from field: string description = 3;
         */
        this.description = "";
        /**
         * @generated from field: repeated string tags = 4;
         */
        this.tags = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new Permission().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Permission().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Permission().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Permission, a, b);
    }
}
exports.Permission = Permission;
Permission.runtime = protobuf_1.proto3;
Permission.typeName = "scalekit.v1.users.Permission";
Permission.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
]);
/**
 * @generated from message scalekit.v1.users.ListUserPermissionsResponse
 */
class ListUserPermissionsResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: repeated scalekit.v1.users.Permission permissions = 1;
         */
        this.permissions = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListUserPermissionsResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListUserPermissionsResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListUserPermissionsResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListUserPermissionsResponse, a, b);
    }
}
exports.ListUserPermissionsResponse = ListUserPermissionsResponse;
ListUserPermissionsResponse.runtime = protobuf_1.proto3;
ListUserPermissionsResponse.typeName = "scalekit.v1.users.ListUserPermissionsResponse";
ListUserPermissionsResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "permissions", kind: "message", T: Permission, repeated: true },
]);
//# sourceMappingURL=users_pb.js.map