"use strict";
// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file scalekit/v1/users/users.proto (package scalekit.v1.users, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserService = void 0;
const users_pb_js_1 = require("./users_pb.js");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service scalekit.v1.users.UserService
 */
exports.UserService = {
    typeName: "scalekit.v1.users.UserService",
    methods: {
        /**
         * Users
         *
         * @generated from rpc scalekit.v1.users.UserService.GetUser
         */
        getUser: {
            name: "GetUser",
            I: users_pb_js_1.GetUserRequest,
            O: users_pb_js_1.GetUserResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.ListUsers
         */
        listUsers: {
            name: "ListUsers",
            I: users_pb_js_1.ListUsersRequest,
            O: users_pb_js_1.ListUsersResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.SearchUsers
         */
        searchUsers: {
            name: "SearchUsers",
            I: users_pb_js_1.SearchUsersRequest,
            O: users_pb_js_1.SearchUsersResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.SearchOrganizationUsers
         */
        searchOrganizationUsers: {
            name: "SearchOrganizationUsers",
            I: users_pb_js_1.SearchOrganizationUsersRequest,
            O: users_pb_js_1.SearchOrganizationUsersResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.UpdateUser
         */
        updateUser: {
            name: "UpdateUser",
            I: users_pb_js_1.UpdateUserRequest,
            O: users_pb_js_1.UpdateUserResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.DeleteUser
         */
        deleteUser: {
            name: "DeleteUser",
            I: users_pb_js_1.DeleteUserRequest,
            O: protobuf_1.Empty,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * Memberships
         *
         * @generated from rpc scalekit.v1.users.UserService.CreateMembership
         */
        createMembership: {
            name: "CreateMembership",
            I: users_pb_js_1.CreateMembershipRequest,
            O: users_pb_js_1.CreateMembershipResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * TODO Check cascade behaviour currently its ignored
         *
         * @generated from rpc scalekit.v1.users.UserService.DeleteMembership
         */
        deleteMembership: {
            name: "DeleteMembership",
            I: users_pb_js_1.DeleteMembershipRequest,
            O: protobuf_1.Empty,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.UpdateMembership
         */
        updateMembership: {
            name: "UpdateMembership",
            I: users_pb_js_1.UpdateMembershipRequest,
            O: users_pb_js_1.UpdateMembershipResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.CreateUserAndMembership
         */
        createUserAndMembership: {
            name: "CreateUserAndMembership",
            I: users_pb_js_1.CreateUserAndMembershipRequest,
            O: users_pb_js_1.CreateUserAndMembershipResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * only memberships of the organization
         *
         * @generated from rpc scalekit.v1.users.UserService.ListOrganizationUsers
         */
        listOrganizationUsers: {
            name: "ListOrganizationUsers",
            I: users_pb_js_1.ListOrganizationUsersRequest,
            O: users_pb_js_1.ListOrganizationUsersResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.ResendInvite
         */
        resendInvite: {
            name: "ResendInvite",
            I: users_pb_js_1.ResendInviteRequest,
            O: users_pb_js_1.ResendInviteResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * User Role Management
         *
         * @generated from rpc scalekit.v1.users.UserService.ListUserRoles
         */
        listUserRoles: {
            name: "ListUserRoles",
            I: users_pb_js_1.ListUserRolesRequest,
            O: users_pb_js_1.ListUserRolesResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.AssignUserRoles
         */
        assignUserRoles: {
            name: "AssignUserRoles",
            I: users_pb_js_1.AssignUserRolesRequest,
            O: users_pb_js_1.AssignUserRolesResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.RemoveUserRole
         */
        removeUserRole: {
            name: "RemoveUserRole",
            I: users_pb_js_1.RemoveUserRoleRequest,
            O: protobuf_1.Empty,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc scalekit.v1.users.UserService.ListUserPermissions
         */
        listUserPermissions: {
            name: "ListUserPermissions",
            I: users_pb_js_1.ListUserPermissionsRequest,
            O: users_pb_js_1.ListUserPermissionsResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
//# sourceMappingURL=users_connect.js.map