// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file workspaces.proto (package scalekit.v1.workspaces, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateWorkspaceRequest, CreateWorkspaceResponse, GetCurrentWorkspaceRequest, GetWorkspaceRequest, GetWorkspaceResponse, UpdateCurrentWorkspaceRequest, UpdateWorkspaceRequest, UpdateWorkspaceResponse } from "./workspaces_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scalekit.v1.workspaces.WorkspaceService
 */
export const WorkspaceService = {
  typeName: "scalekit.v1.workspaces.WorkspaceService",
  methods: {
    /**
     * @generated from rpc scalekit.v1.workspaces.WorkspaceService.CreateWorkspace
     */
    createWorkspace: {
      name: "CreateWorkspace",
      I: CreateWorkspaceRequest,
      O: CreateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.workspaces.WorkspaceService.GetWorkspace
     */
    getWorkspace: {
      name: "GetWorkspace",
      I: GetWorkspaceRequest,
      O: GetWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.workspaces.WorkspaceService.GetCurrentWorkspace
     */
    getCurrentWorkspace: {
      name: "GetCurrentWorkspace",
      I: GetCurrentWorkspaceRequest,
      O: GetWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.workspaces.WorkspaceService.UpdateWorkspace
     */
    updateWorkspace: {
      name: "UpdateWorkspace",
      I: UpdateWorkspaceRequest,
      O: UpdateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.workspaces.WorkspaceService.UpdateCurrentWorkspace
     */
    updateCurrentWorkspace: {
      name: "UpdateCurrentWorkspace",
      I: UpdateCurrentWorkspaceRequest,
      O: UpdateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

