"use strict";
// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file scalekit/v1/auditlogs/auditlogs.proto (package scalekit.v1.auditlogs, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConnectionDetails = exports.AuthLogRequest = exports.ListAuthLogResponse = exports.ListAuthLogRequest = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from message scalekit.v1.auditlogs.ListAuthLogRequest
 */
class ListAuthLogRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: uint32 page_size = 1;
         */
        this.pageSize = 0;
        /**
         * @generated from field: string page_token = 2;
         */
        this.pageToken = "";
        /**
         * @generated from field: string email = 3;
         */
        this.email = "";
        /**
         * @generated from field: repeated string status = 4;
         */
        this.status = [];
        /**
         * @generated from field: string resource_id = 7;
         */
        this.resourceId = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListAuthLogRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListAuthLogRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListAuthLogRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListAuthLogRequest, a, b);
    }
}
exports.ListAuthLogRequest = ListAuthLogRequest;
ListAuthLogRequest.runtime = protobuf_1.proto3;
ListAuthLogRequest.typeName = "scalekit.v1.auditlogs.ListAuthLogRequest";
ListAuthLogRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "start_time", kind: "message", T: protobuf_1.Timestamp },
    { no: 6, name: "end_time", kind: "message", T: protobuf_1.Timestamp },
    { no: 7, name: "resource_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.auditlogs.ListAuthLogResponse
 */
class ListAuthLogResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string next_page_token = 1;
         */
        this.nextPageToken = "";
        /**
         * @generated from field: string prev_page_token = 2;
         */
        this.prevPageToken = "";
        /**
         * @generated from field: uint32 total_size = 3;
         */
        this.totalSize = 0;
        /**
         * @generated from field: repeated scalekit.v1.auditlogs.AuthLogRequest authRequests = 4;
         */
        this.authRequests = [];
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ListAuthLogResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListAuthLogResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListAuthLogResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListAuthLogResponse, a, b);
    }
}
exports.ListAuthLogResponse = ListAuthLogResponse;
ListAuthLogResponse.runtime = protobuf_1.proto3;
ListAuthLogResponse.typeName = "scalekit.v1.auditlogs.ListAuthLogResponse";
ListAuthLogResponse.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "prev_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "total_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "authRequests", kind: "message", T: AuthLogRequest, repeated: true },
]);
/**
 * @generated from message scalekit.v1.auditlogs.AuthLogRequest
 */
class AuthLogRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string organization_id = 1;
         */
        this.organizationId = "";
        /**
         * @generated from field: string environment_id = 2;
         */
        this.environmentId = "";
        /**
         * @generated from field: string connection_id = 3;
         */
        this.connectionId = "";
        /**
         * @generated from field: string auth_request_id = 4;
         */
        this.authRequestId = "";
        /**
         * @generated from field: string email = 5;
         */
        this.email = "";
        /**
         * @generated from field: string connection_type = 6;
         */
        this.connectionType = "";
        /**
         * @generated from field: string connection_provider = 7;
         */
        this.connectionProvider = "";
        /**
         * @generated from field: string status = 8;
         */
        this.status = "";
        /**
         * @generated from field: repeated scalekit.v1.auditlogs.ConnectionDetails connection_details = 10;
         */
        this.connectionDetails = [];
        /**
         * @generated from field: string workflow = 11;
         */
        this.workflow = "";
        /**
         * @generated from field: string resource_id = 12;
         */
        this.resourceId = "";
        /**
         * @generated from field: string resource_name = 13;
         */
        this.resourceName = "";
        /**
         * @generated from field: string resource_type = 14;
         */
        this.resourceType = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new AuthLogRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AuthLogRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AuthLogRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AuthLogRequest, a, b);
    }
}
exports.AuthLogRequest = AuthLogRequest;
AuthLogRequest.runtime = protobuf_1.proto3;
AuthLogRequest.typeName = "scalekit.v1.auditlogs.AuthLogRequest";
AuthLogRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "environment_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "connection_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "auth_request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "connection_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "connection_provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "timestamp", kind: "message", T: protobuf_1.Timestamp },
    { no: 10, name: "connection_details", kind: "message", T: ConnectionDetails, repeated: true },
    { no: 11, name: "workflow", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "resource_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "resource_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "resource_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message scalekit.v1.auditlogs.ConnectionDetails
 */
class ConnectionDetails extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string connection_id = 1;
         */
        this.connectionId = "";
        /**
         * @generated from field: string organization_id = 2;
         */
        this.organizationId = "";
        /**
         * @generated from field: string connection_type = 3;
         */
        this.connectionType = "";
        /**
         * @generated from field: string connection_provider = 4;
         */
        this.connectionProvider = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new ConnectionDetails().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ConnectionDetails().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ConnectionDetails().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ConnectionDetails, a, b);
    }
}
exports.ConnectionDetails = ConnectionDetails;
ConnectionDetails.runtime = protobuf_1.proto3;
ConnectionDetails.typeName = "scalekit.v1.auditlogs.ConnectionDetails";
ConnectionDetails.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "connection_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "connection_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "connection_provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
//# sourceMappingURL=auditlogs_pb.js.map