// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file scalekit/v1/sessions/sessions.proto (package scalekit.v1.sessions, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RevokeAllUserSessionsRequest, RevokeAllUserSessionsResponse, RevokeSessionRequest, RevokeSessionResponse, SessionDetails, SessionDetailsRequest, UserSessionDetails, UserSessionDetailsRequest } from "./sessions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scalekit.v1.sessions.SessionService
 */
export const SessionService = {
  typeName: "scalekit.v1.sessions.SessionService",
  methods: {
    /**
     * @generated from rpc scalekit.v1.sessions.SessionService.GetSession
     */
    getSession: {
      name: "GetSession",
      I: SessionDetailsRequest,
      O: SessionDetails,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.sessions.SessionService.RevokeSession
     */
    revokeSession: {
      name: "RevokeSession",
      I: RevokeSessionRequest,
      O: RevokeSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.sessions.SessionService.GetUserSessions
     */
    getUserSessions: {
      name: "GetUserSessions",
      I: UserSessionDetailsRequest,
      O: UserSessionDetails,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scalekit.v1.sessions.SessionService.RevokeAllUserSessions
     */
    revokeAllUserSessions: {
      name: "RevokeAllUserSessions",
      I: RevokeAllUserSessionsRequest,
      O: RevokeAllUserSessionsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

